const trials = {
	BEL_0103_AMAZING: {code: "BEL_0103_AMAZING",sentence: "These brown mushrooms taste amazing."},
	BEL_0104_DANGEROUS: {code: "BEL_0104_DANGEROUS",sentence: "The train is fast and very dangerous."},
	BEL_0111_ALIVE: {code: "BEL_0111_ALIVE",sentence: "The weak plant is barely alive."},
	BEL_0114_SALT: {code: "BEL_0114_SALT",sentence: "The eggs need more salt."},
	BEL_0115_HOME: {code: "BEL_0115_HOME",sentence: "The old men missed home."},
	BEL_0120_TOYS: {code: "BEL_0120_TOYS",sentence: "His sister plays with beautiful toys."},
	BEL_0124_WEEKEND: {code: "BEL_0124_WEEKEND",sentence: "The bar sells beer on the weekend."},
	BEL_0201_GRANDPARENTS: {code: "BEL_0201_GRANDPARENTS",sentence: "The twins live with their grandparents."},
	BEL_0204_AWAY: {code: "BEL_0204_AWAY",sentence: "That bright light seems far away."},
	BEL_0214_STREET: {code: "BEL_0214_STREET",sentence: "The lady walked down the street."},
	BEL_0216_CHILD: {code: "BEL_0216_CHILD",sentence: "The scary monkey chased the child."},
	BEL_0218_FRESH: {code: "BEL_0218_FRESH",sentence: "The fruit and salad taste fresh."},
	BEL_0220_CRUEL: {code: "BEL_0220_CRUEL",sentence: "Her grandparents are serious and sometimes cruel."},
	BEL_0317_WINDOW: {code: "BEL_0317_WINDOW",sentence: "The baseball broke a glass window."},
	BEL_0322_MORNING: {code: "BEL_0322_MORNING",sentence: "The bird sings songs in the morning."},
	BEL_0402_DAUGHTER: {code: "BEL_0402_DAUGHTER",sentence: "The father hugs his sad daughter."},
	BEL_0406_PARENTS: {code: "BEL_0406_PARENTS",sentence: "The rude joke upset my parents."},
	BEL_0414_WINDOW: {code: "BEL_0414_WINDOW",sentence: "The tomato plant grew by the window."},
	BEL_0417_HOME: {code: "BEL_0417_HOME",sentence: "The worried adult ran home."},
	BEL_0418_WEEKEND: {code: "BEL_0418_WEEKEND",sentence: "The newspaper comes every weekend."},
	BEL_0419_SONGS: {code: "BEL_0419_SONGS",sentence: "The talented musician knows many songs."},
	BEL_0420_GRASS: {code: "BEL_0420_GRASS",sentence: "The gray horse eats grass."},
	BEL_0423_WINE: {code: "BEL_0423_WINE",sentence: "The customer enjoyed the meal and wine."},
	BEL_0605_BABY: {code: "BEL_0605_BABY",sentence: "The strange animal scared the baby."},
	BEL_0613_FLOOR: {code: "BEL_0613_FLOOR",sentence: "The fat pig slept on the floor."},
	BEL_0617_BOX: {code: "BEL_0617_BOX",sentence: "The teenager lifted a heavy box."},
	BEL_0619_WATER: {code: "BEL_0619_WATER",sentence: "That man swims in the cold water."},
	BEL_0620_FIELD: {code: "BEL_0620_FIELD",sentence: "The baseball flew across the field."},
	BEL_0715_MORNING: {code: "BEL_0715_MORNING",sentence: "The news was on tv every morning."},
	BEL_0719_ROOM: {code: "BEL_0719_ROOM",sentence: "The people sit in the living room."},
	BEL_0720_WATER: {code: "BEL_0720_WATER",sentence: "The clean beaches have clear water."},
	BEL_0724_NOVEL: {code: "BEL_0724_NOVEL",sentence: "The professor read an interesting novel."},
	BEL_0804_EDUCATION: {code: "BEL_0804_EDUCATION",sentence: "The workers need better education."},
	BEL_0806_SCHOOL: {code: "BEL_0806_SCHOOL",sentence: "Her apartment was near the private school."},
	BEL_0811_CLOSE: {code: "BEL_0811_CLOSE",sentence: "The wooden door was hard to close."},
	BEL_0812_CARS: {code: "BEL_0812_CARS",sentence: "They bought three blue cars."},
	BEL_0823_PRIZE: {code: "BEL_0823_PRIZE",sentence: "That pretty girl won a prize."},
	BEL_0904_WELL: {code: "BEL_0904_WELL",sentence: "Their famous son danced well."},
	BEL_0908_TRIP: {code: "BEL_0908_TRIP",sentence: "The best worker went on the trip."},
	BEL_0911_SCIENCE: {code: "BEL_0911_SCIENCE",sentence: "The class learned about earth science."},
	BEL_0916_PERFORMER: {code: "BEL_0916_PERFORMER",sentence: "The crowd watched the talented performer."},
	BEL_0920_STORIES: {code: "BEL_0920_STORIES",sentence: "Some writers tell interesting stories."},
	BEL_0921_SCARY: {code: "BEL_0921_SCARY",sentence: "The black bear was big and scary."},
	BEL_1002_COURSES: {code: "BEL_1002_COURSES",sentence: "These colleges offer many courses."},
	BEL_1008_MILK: {code: "BEL_1008_MILK",sentence: "The thirsty cat drank milk."},
	BEL_1009_EXAM: {code: "BEL_1009_EXAM",sentence: "The young student took the final exam."},
	BEL_1011_THIN: {code: "BEL_1011_THIN",sentence: "The white onion was cut too thin."},
	BEL_1016_ATTENTION: {code: "BEL_1016_ATTENTION",sentence: "The noisy group attracts attention."},
	BEL_1020_LAKE: {code: "BEL_1020_LAKE",sentence: "The lonely duck swims in the lake."},
	BEL_1101_MINUTES: {code: "BEL_1101_MINUTES",sentence: "The meeting starts in twenty minutes."},
	BEL_1102_TEA: {code: "BEL_1102_TEA",sentence: "The customers hate black tea."},
	BEL_1104_HERE: {code: "BEL_1104_HERE",sentence: "That brown bird is always here."},
	BEL_1105_HOMEWORK: {code: "BEL_1105_HOMEWORK",sentence: "The three cousins did their math homework."},
	BEL_1108_ROOM: {code: "BEL_1108_ROOM",sentence: "The movie started in the small room."},
	BEL_1111_LATE: {code: "BEL_1111_LATE",sentence: "The birthday card was sent late."},
	BEL_1204_PATIENT: {code: "BEL_1204_PATIENT",sentence: "The doctor helped the sick patient."},
	BEL_1210_AIR: {code: "BEL_1210_AIR",sentence: "The strong wind cooled the air."},
	BEL_1211_ANGRY: {code: "BEL_1211_ANGRY",sentence: "The terrible customer was loud and angry."},
	BEL_1212_UPSET: {code: "BEL_1212_UPSET",sentence: "Her youngest son was always upset."},
	BEL_1217_HAIR: {code: "BEL_1217_HAIR",sentence: "She washed and dried her curly hair."},
	BEL_1220_STORY: {code: "BEL_1220_STORY",sentence: "The happy children laugh at the story."},
	BEL_1222_YEAR: {code: "BEL_1222_YEAR",sentence: "They took a school picture every year."},
	BEL_1304_PROJECT: {code: "BEL_1304_PROJECT",sentence: "The boss assigned a difficult project."},
	BEL_1311_CHAIR: {code: "BEL_1311_CHAIR",sentence: "The kitten sat on the wooden chair."},
	BEL_1313_HOURS: {code: "BEL_1313_HOURS",sentence: "The party lasted for three hours."},
	BEL_1319_WATER: {code: "BEL_1319_WATER",sentence: "The pasta boiled in the hot water."},
	BEL_1322_TRUTH: {code: "BEL_1322_TRUTH",sentence: "A good friend tells the truth."},
	BEL_1410_THIN: {code: "BEL_1410_THIN",sentence: "Their youngest daughter is tall and thin."},
	BEL_1414_HOME: {code: "BEL_1414_HOME",sentence: "The foreign lady dreamed of her home."},
	BEL_1416_TODAY: {code: "BEL_1416_TODAY",sentence: "The little girl was angry today."},
	BEL_1418_TREE: {code: "BEL_1418_TREE",sentence: "The happy monkey swings from the tree."},
	BEL_1419_SPORTS: {code: "BEL_1419_SPORTS",sentence: "The club members played sports."},
	BEL_1422_MOVIE: {code: "BEL_1422_MOVIE",sentence: "The twin sisters watched a movie."},
	BEL_1507_HELP: {code: "BEL_1507_HELP",sentence: "The unhappy child needs help."},
	BEL_1509_LUNCH: {code: "BEL_1509_LUNCH",sentence: "The vegetable soup was a healthy lunch."},
	BEL_1519_THEATER: {code: "BEL_1519_THEATER",sentence: "The actor sang loudly in the theater."},
	BEL_1523_PAN: {code: "BEL_1523_PAN",sentence: "They roasted salty meat in the pan."},
	BEL_1524_TODAY: {code: "BEL_1524_TODAY",sentence: "Those little kids are tired today."},
	BEL_1611_SWEET: {code: "BEL_1611_SWEET",sentence: "The cherry pie was warm and sweet."},
	BEL_1616_BANANAS: {code: "BEL_1616_BANANAS",sentence: "The monkey wants yellow bananas."},
	BEL_1707_MOUNTAIN: {code: "BEL_1707_MOUNTAIN",sentence: "The two friends hiked up the mountain."},
	BEL_1710_UGLY: {code: "BEL_1710_UGLY",sentence: "The blue hat was strange and ugly."},
	BEL_1715_MUSIC: {code: "BEL_1715_MUSIC",sentence: "The group heard slow music."},
	BEL_1719_GARDEN: {code: "BEL_1719_GARDEN",sentence: "The vegetables grew in the green garden."},
	BEL_1721_POOL: {code: "BEL_1721_POOL",sentence: "The hot sun warmed the pool."},
	BEL_1722_SALAD: {code: "BEL_1722_SALAD",sentence: "The chicken sandwich came with salad."},
	BEL_1723_BROKEN: {code: "BEL_1723_BROKEN",sentence: "The ten gifts were completely broken."},
	BEL_1806_MEAT: {code: "BEL_1806_MEAT",sentence: "The butcher sells italian meat."},
	BEL_1813_HELP: {code: "BEL_1813_HELP",sentence: "The sick neighbor asks for help."},
	BEL_1818_BOX: {code: "BEL_1818_BOX",sentence: "The keys disappeared in the orange box."},
	BEL_1907_BED: {code: "BEL_1907_BED",sentence: "The puppy slept peacefully on the bed."},
	BEL_1911_STORIES: {code: "BEL_1911_STORIES",sentence: "Their neighbors tell interesting stories."},
	BEL_1919_NEWSPAPER: {code: "BEL_1919_NEWSPAPER",sentence: "Our business paid for the daily newspaper."},
	BEL_2009_QUESTIONS: {code: "BEL_2009_QUESTIONS",sentence: "The teacher chooses difficult questions."},
	BEL_2010_COLD: {code: "BEL_2010_COLD",sentence: "That deep lake is quite cold."},
	BEL_2023_SOON: {code: "BEL_2023_SOON",sentence: "The funny movie will end soon."}
}

const aligned_trial_list = [
	{	
		BBQ_0501_BANJO: {code: "BBQ_0501_BANJO", sentence: "Our uncle plays the banjo."},
		BBQ_0502_SMOKER: {code: "BBQ_0502_SMOKER", sentence: "The ribs are in the smoker."},
		BBQ_0503_SAUCE: {code: "BBQ_0503_SAUCE", sentence: "The brisket is good with barbecue sauce."},
		BBQ_0504_GOLDEN: {code: "BBQ_0504_GOLDEN", sentence: "The corn stalks are tall and golden."},
		BBQ_0505_JARS: {code: "BBQ_0505_JARS", sentence: "The sweet tea is in mason jars."},
		BBQ_0507_PASTURE: {code: "BBQ_0507_PASTURE", sentence: "The horses are grazing in the pasture."},
		BBQ_0509_SHIRT: {code: "BBQ_0509_SHIRT", sentence: "She wore a straw hat and plaid shirt."},
		BBQ_0510_SWING: {code: "BBQ_0510_SWING", sentence: "The barn cat purred on the porch swing."}
	},
	{
		JAZ_0401_ROOM: {code: "JAZ_0401_ROOM", sentence: "The trumpet solo lit up the room."},
		JAZ_0402_SPOTLIGHT: {code: "JAZ_0402_SPOTLIGHT", sentence: "The drummer was lit by a spotlight."},
		JAZ_0403_PEG: {code: "JAZ_0403_PEG", sentence: "He spun his upright bass on its peg."},
		JAZ_0405_STAGE: {code: "JAZ_0405_STAGE", sentence: "The musicians wore sunglasses on stage."},
		JAZ_0406_EXPLOSIVE: {code: "JAZ_0406_EXPLOSIVE", sentence: "The saxophone solo was explosive."},
		JAZ_0407_MICROPHONE: {code: "JAZ_0407_MICROPHONE", sentence: "She sang into an old microphone."},
		JAZ_0409_SOULFUL: {code: "JAZ_0409_SOULFUL", sentence: "The melody was warm and soulful."},
		JAZ_0410_HEART: {code: "JAZ_0410_HEART", sentence: "Jazz has to come from the heart."}
	},
	{
		NYC_0901_SALS: {code: "NYC_0901_SALS", sentence: "The best pizza is at Sal's."},
		NYC_0902_BRIDGE: {code: "NYC_0902_BRIDGE", sentence: "You have to take the Brooklyn Bridge."},
		NYC_0903_HOUR: {code: "NYC_0903_HOUR", sentence: "The cannolis are fresh every hour."},
		NYC_0904_BROADWAY: {code: "NYC_0904_BROADWAY", sentence: "The yellow cabs were on Broadway."},
		NYC_0905_LATE: {code: "NYC_0905_LATE", sentence: "The Staten Island Ferry left late."},
		NYC_0906_MOZZARELLA: {code: "NYC_0906_MOZZARELLA", sentence: "The deli sells fresh mozzarella."},
		NYC_0907_YANKEES: {code: "NYC_0907_YANKEES", sentence: "He was yelling about the Yankees."},
		NYC_0909_NEWYEARS: {code: "NYC_0909_NEWYEARS", sentence: "Times Square is bustling around New Year's."}
	},
	{
		RET_0301_SCARVES: {code: "RET_0301_SCARVES", sentence: "The women were knitting scarves."},
		RET_0302_YARN: {code: "RET_0302_YARN", sentence: "The basket was full of pink yarn."},
		RET_0303_CHAPEL: {code: "RET_0303_CHAPEL", sentence: "The knitting group met in the chapel."},
		RET_0304_BEAR: {code: "RET_0304_BEAR", sentence: "She crocheted a teddy bear."},
		RET_0305_BINGO: {code: "RET_0305_BINGO", sentence: "The elderly people played bingo."},
		RET_0307_NEEDLES: {code: "RET_0307_NEEDLES", sentence: "She knits with wooden needles."},
		RET_0308_SWEATER: {code: "RET_0308_SWEATER", sentence: "She tried on a homemade sweater."},
		RET_0310_SOCKS: {code: "RET_0310_SOCKS", sentence: "She made her granddaughter wool socks."}
	}
]